name: Dependabot Alerts Today

on:
  workflow_dispatch:

jobs:
  get-todays-dependabot-alerts:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Obtener alertas de Dependabot creadas hoy
        uses: actions/github-script@v7
        with:
          script: |
            const org = 'Taller-DevSecOps'; 
            const alerts = await github.paginate(
              github.rest.dependabot.listAlertsForOrg,
              {
                org,
                per_page: 100,
                state: "open"
              }
            );

            const today = new Date().toISOString().split('T')[0]; // Formato YYYY-MM-DD
            const todaysAlerts = alerts.filter(alert => alert.created_at.startsWith(today));

            if (todaysAlerts.length === 0) {
              console.log("✅ No hay nuevas alertas de Dependabot hoy.");
            } else {
              console.log(`🚨 ${todaysAlerts.length} nuevas alertas creadas hoy:\n`);
              todaysAlerts.forEach(alert => {
                console.log(`- ${alert.security_advisory.summary} [${alert.dependency.package.ecosystem}]`);
              });
            }
