name: Dependabot Alerts Today

on:
  workflow_dispatch:

jobs:
  get-todays-dependabot-alerts:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Obtener alertas de Dependabot creadas hoy
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.AUTH_TOKEN }}
          script: |
            const org = 'Taller-DevSecOps'; 
            const alerts = await github.paginate(
              github.rest.dependabot.listAlertsForOrg,
              {
                org,
                per_page: 100,
                state: "open"
              }
            );

            const today = new Date().toISOString().split('T')[0]; // Formato YYYY-MM-DD
            const todaysAlerts = alerts.filter(alert => alert.created_at.startsWith(today));

            if (todaysAlerts.length === 0) {
              console.log("✅ No hay nuevas alertas de Dependabot hoy.");
            } else {
              console.log(`🚨 ${todaysAlerts.length} nuevas alertas creadas hoy:\n`);
              todaysAlerts.forEach(alert => {
                const advisory = alert.security_advisory;
                const cve = advisory.identifiers.find(id => id.type === 'CVE')?.value || 'Sin CVE';
                const severity = advisory.severity || 'Desconocida';
                const cvss = advisory.cvss?.score || 'No disponible';
                const summary = advisory.summary;
                const ecosystem = alert.dependency.package.ecosystem;

                console.log(`- ${summary} [${ecosystem}]`);
                console.log(`  📛 CVE: ${cve}`);
                console.log(`  ⚠️ Severidad: ${severity}`);
                console.log(`  🧮 CVSS: ${cvss}\n`);
              });
            }
